# Generated by Django 5.0.4 on 2024-04-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_emotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotion',
            old_name='text',
            new_name='thoughts',
        ),
    ]
