# Generated by Django 5.0.4 on 2024-04-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_rename_text_emotion_thoughts'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='emotions',
            field=models.CharField(default='temporary', max_length=1000),
            preserve_default=False,
        ),
    ]
